### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by espeed** [janimo/textsecure#9] opened 2015-04-11 16:34 UTC
Also see https://github.com/golang/go/issues/7227

```
$ GOTRACEBACK=2 ./textsecure -echo=true
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
runtime.gopanic(0x779980, 0xc20802a010)
	/usr/local/go/src/runtime/panic.go:425 +0x2a3 fp=0xc2080816e0 sp=0xc208081678
runtime.panicslice()
	/usr/local/go/src/runtime/panic.go:18 +0x4e fp=0xc208081708 sp=0xc2080816e0
github.com/janimo/textsecure/axolotl.Decrypt(0xc20802ed20, 0x20, 0x50, 0xc208082b00, 0xb0, 0xb0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/james/go/src/github.com/janimo/textsecure/axolotl/crypto.go:38 +0x361 fp=0xc2080817b8 sp=0xc208081708
github.com/janimo/textsecure/axolotl.(*SessionCipher).decrypt(0xc20803ae80, 0xc2080a80f0, 0xc20802ea50, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/james/go/src/github.com/janimo/textsecure/axolotl/session.go:571 +0x670 fp=0xc208081908 sp=0xc2080817b8
github.com/janimo/textsecure/axolotl.(*SessionCipher).SessionDecryptWhisperMessage(0xc20803ae80, 0xc20802ea50, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/james/go/src/github.com/janimo/textsecure/axolotl/session.go:587 +0x123 fp=0xc208081990 sp=0xc208081908
github.com/janimo/textsecure.handleReceivedMessage(0xc208072240, 0x11b, 0x11b, 0x0, 0x0)
	/home/james/go/src/github.com/janimo/textsecure/textsecure.go:345 +0x6fc fp=0xc208081cb8 sp=0xc208081990
github.com/janimo/textsecure.ListenForMessages(0x0, 0x0)
	/home/james/go/src/github.com/janimo/textsecure/websocket.go:151 +0x52a fp=0xc208081dd8 sp=0xc208081cb8
main.main()
	/home/james/go/src/github.com/janimo/textsecure/cmd/textsecure/main.go:238 +0x905 fp=0xc208081f98 sp=0xc208081dd8
runtime.main()
	/usr/local/go/src/runtime/proc.go:63 +0xf3 fp=0xc208081fe0 sp=0xc208081f98
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208081fe8 sp=0xc208081fe0

goroutine 2 [force gc (idle)]:
runtime.gopark(0x4350f0, 0x9cc5e0, 0x8015f0, 0xf)
	/usr/local/go/src/runtime/proc.go:130 +0x105 fp=0xc20801a798 sp=0xc20801a768
runtime.goparkunlock(0x9cc5e0, 0x8015f0, 0xf)
	/usr/local/go/src/runtime/proc.go:136 +0x48 fp=0xc20801a7c0 sp=0xc20801a798
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:99 +0xce fp=0xc20801a7e0 sp=0xc20801a7c0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801a7e8 sp=0xc20801a7e0
created by runtime.init·4
	/usr/local/go/src/runtime/proc.go:87 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x4350f0, 0x9d5058, 0x7f6f10, 0xd)
	/usr/local/go/src/runtime/proc.go:130 +0x105 fp=0xc20801df98 sp=0xc20801df68
runtime.goparkunlock(0x9d5058, 0x7f6f10, 0xd)
	/usr/local/go/src/runtime/proc.go:136 +0x48 fp=0xc20801dfc0 sp=0xc20801df98
runtime.bgsweep()
	/usr/local/go/src/runtime/mgc0.go:98 +0xbc fp=0xc20801dfe0 sp=0xc20801dfc0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801dfe8 sp=0xc20801dfe0
created by gc
	/usr/local/go/src/runtime/mgc0.c:1383

goroutine 4 [finalizer wait]:
runtime.gopark(0x4350f0, 0x9d5050, 0x800e70, 0xe)
	/usr/local/go/src/runtime/proc.go:130 +0x105 fp=0xc208018f30 sp=0xc208018f00
runtime.goparkunlock(0x9d5050, 0x800e70, 0xe)
	/usr/local/go/src/runtime/proc.go:136 +0x48 fp=0xc208018f58 sp=0xc208018f30
runtime.runfinq()
	/usr/local/go/src/runtime/malloc.go:727 +0xba fp=0xc208018fe0 sp=0xc208018f58
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208018fe8 sp=0xc208018fe0
created by runtime.createfing
	/usr/local/go/src/runtime/malloc.go:707 +0x5e

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208058fe8 sp=0xc208058fe0

goroutine 5 [sleep]:
runtime.gopark(0x4350f0, 0x9cc840, 0x7efa40, 0x5)
	/usr/local/go/src/runtime/proc.go:130 +0x105 fp=0xc20807bed0 sp=0xc20807bea0
runtime.goparkunlock(0x9cc840, 0x7efa40, 0x5)
	/usr/local/go/src/runtime/proc.go:136 +0x48 fp=0xc20807bef8 sp=0xc20807bed0
runtime.timeSleep(0x37e11d600)
	/usr/local/go/src/runtime/time.go:58 +0x105 fp=0xc20807bf30 sp=0xc20807bef8
github.com/janimo/textsecure.(*wsConn).keepAlive(0xc20802ab90)
	/home/james/go/src/github.com/janimo/textsecure/websocket.go:88 +0x163 fp=0xc20807bfd8 sp=0xc20807bf30
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20807bfe0 sp=0xc20807bfd8
created by github.com/janimo/textsecure.ListenForMessages
	/home/james/go/src/github.com/janimo/textsecure/websocket.go:134 +0x210

goroutine 6 [syscall]:
runtime.notetsleepg(0x9cc858, 0x37e11c8d7, 0x0)
	/usr/local/go/src/runtime/lock_futex.go:201 +0x52 fp=0xc208019768 sp=0xc208019740
runtime.timerproc()
	/usr/local/go/src/runtime/time.go:207 +0xfa fp=0xc2080197e0 sp=0xc208019768
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080197e8 sp=0xc2080197e0
created by runtime.addtimerLocked
	/usr/local/go/src/runtime/time.go:113 +0x1ba
```

**Comment by janimo** [comment] 2015-04-13 07:19
What go version and platform?

**Comment by espeed** [comment] 2015-04-13 18:53
```
$ go version
go version go1.4 linux/amd64

$ uname -a
Linux life 3.19.3-200.fc21.x86_64 #1 SMP Thu Mar 26 21:39:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/issue
Fedora release 21 (Twenty One)
```

**Comment by janimo** [comment] 2015-04-18 12:01
I cannot reproduce this, but it looks like a corrupted message is being received. We should probably not panic here though. Can you describe how this is reproduced ? Which clients are you communicating with?

**Comment by janimo** [comment] 2015-04-20 09:18
What is the connection to the golang bug you linked to?

**Comment by espeed** [comment] 2015-04-20 12:54
The error persisted after a reboot. To fix it, I deleted the `.storage` directory and re-ran `cmd/textsecure`.

**Comment by janimo** [comment] 2015-04-20 12:56
I added some checks in the tree, so now it will error instead of panicking but it looks like it was a corrupted message, possibly sent by older/incompatible clients. Or just a bug I'll run into later. Closing for now.

**Closed by janimo** 2015-04-20 12:56 UTC

**Comment by elimisteve** [comment] 2015-08-16 04:10
@janimo Note that this will panic if len(msg) < 10:

```
func handleReceivedMessage(msg []byte) error {
    macpos := len(msg) - 10
    tmac := msg[macpos:]
    ...
}
```

which would cause a slice panic like the one experienced by @espeed.

**Comment by janimo** [comment] 2015-08-16 16:05
The message is received from the server, so in theory should not be that short as long, but I agree more defensive checks in the code would not hurt.
